CREATE INDEX IDX_UBIGEO_INEI_UBIGEO ON UBIGEO_INEI (UBIGEO);
CREATE INDEX IDX_UBIGEO_INEI_DEP_PROV_DIST ON UBIGEO_INEI (DEPARTAMENTO, PROVINCIA, DISTRITO);
CREATE INDEX IDX_UBIGEO_INEI_DEPARTAMENTO ON UBIGEO_INEI (DEPARTAMENTO);
CREATE INDEX IDX_UBIGEO_INEI_PROVINCIA ON UBIGEO_INEI (PROVINCIA);
